### ISSUE TITLE
please tell us how to run it in README.md, thanks a lot bro

### ISSUE THREAD

**Issue by GoogTech** [supergithuber/WeatherMessage#3]

**Comment by supergithuber** [comment]
Chinese？I think it's quiet easy for programer.
1. python3 environment
2. install requirements
3. python run

**Comment by supergithuber** [comment]
> _No description provided._

Chinese？I think it's quiet easy for a programer.
1. python3 environment
2. install requirements
3. python run

**Comment by supergithuber** [comment]
> _No description provided._

**Comment by GoogTech** [comment]
emmm.. thanks bro
